config/routes.rb
Rails.application.routes.draw do

  resources :styles

  resources :breweries
  resources :beers
  resources :ratings
  resources :memberships
  resources :beer_clubs
  resources :users
  get 'signup', to: 'users#new'
  resource :session, only: [:new, :create, :destroy]
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resources :places, only: [:index, :show]
  post 'places', to:'places#search'
    
  root 'breweries#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kaljamaistelut</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navibar">
    <%= link_to 'Breweries', breweries_path %> — 
    <%= link_to 'Beers', beers_path %> — 
    <%= link_to 'Styles', styles_path %> — 
    <%= link_to 'Ratings', ratings_path %> — 
    <%= link_to 'Raters', users_path %> — 
    <%= link_to 'Beer clubs', beer_clubs_path %> — 
    <%= link_to 'Find a place', places_path %> — 
    <% if current_user %>
      Signed in as <%= link_to User.find(session[:user_id]).username, current_user %> — 
      <%= link_to 'Rate a beer', new_rating_path %> — 
      <%= link_to 'Join a club', new_membership_path %> — 
      <%= link_to 'log out', session_path, method: :delete %>
    <% else %>
      <%= link_to 'signIN', new_session_path %> — 
      <%= link_to 'signUP', new_user_path %>
    <% end %>
  </div>
  <p>
  <% if session[:last_rating].nil? %>
    no ratings given
  <% else %>
    previous rating: <%= session[:last_rating] %>
  <% end %>
  </p>
<%= yield %>

</body>
</html>